import urllib.request
xml = '''<ENVELOPE>
<HEADER><VERSION>1</VERSION><TALLYREQUEST>Export</TALLYREQUEST><TYPE>Collection</TYPE><ID>AllVouchers</ID></HEADER>
<BODY><DESC><STATICVARIABLES>
<SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT>
<SVCURRENTCOMPANY>SMRIDHI SPONGE LIMITED - (from 1-Apr-24) - (from 1-Apr-25)</SVCURRENTCOMPANY>
<SVFROMDATE>20260401</SVFROMDATE>
<SVTODATE>20260405</SVTODATE>
</STATICVARIABLES>
<TDL><TDLMESSAGE><COLLECTION NAME="AllVouchers" ISINITIALIZE="Yes"><TYPE>Voucher</TYPE>
<FETCH>VOUCHERTYPENAME,INVENTORYENTRIESIN.LIST.*,INVENTORYENTRIESOUT.LIST.*,ALLINVENTORYENTRIES.LIST.*,INVENTORYENTRIES.LIST.*</FETCH>
</COLLECTION></TDLMESSAGE></TDL></DESC></BODY>
</ENVELOPE>'''
req = urllib.request.Request('http://localhost:9000', data=xml.encode('utf-8'), headers={'Content-Type': 'text/xml'})
res = urllib.request.urlopen(req).read().decode()
print('Has INVENTORYENTRIESIN:', 'INVENTORYENTRIESIN.LIST' in res)
print('Has INVENTORYENTRIESOUT:', 'INVENTORYENTRIESOUT.LIST' in res)
